### ISSUE TITLE
Anaconda doesn't start

### ISSUE THREAD

**Issue by aamrun** [robertdebock/ansible-role-anaconda#1]
ok: [localhost]
 _________________________________________________________
< TASK [robertdebock.service : configure systemd service] >
 ---------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [localhost] => (item=anaconda)
 __________________________________________________________
< TASK [robertdebock.service : configure sysvinit service] >
 ----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

skipping: [localhost] => (item=anaconda)
 ____________________________________________________
/ RUNNING HANDLER [robertdebock.anaconda : systemctl \
\ daemon-reload]                                     /
 ----------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 ________________________________________________________
< TASK [robertdebock.anaconda : modify selinux settings] >
 --------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

skipping: [localhost]
 ________________________________________________
/ TASK [robertdebock.anaconda : start and enable \
\ jupyter-notebook]                              /
 ------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service jupyter-notebook: host"}
        to retry, use: --limit @/home/aamrun/.ansible/roles/robertdebock.anaconda/molecule/resources/playbook.retry
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=11   changed=4    unreachable=0    failed=1

jupyter-notebook is not the correct service name

**Comment by robertdebock** [comment]
Should be fixed with the latest commit. I'll release a version in a moment.
